# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Archive', path: 'menu', url: 'archive.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/kitchenknif'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
